name: namaste-os-bazzite
description: Personal distro by and for JFL

base-image: ghcr.io/ublue-os/bazzite
image-version: 41 # latest is also supported if you want new updates ASAP

modules:

  - type: script
    snippets:
      - "wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/bin/yt-dlp"
      - "chmod a+rx /usr/bin/yt-dlp"

  - type: rpm-ostree
    repos: # 
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      - bridge-utils 
      - htop
      - clblast 
      - clblast-devel 
      - distrobox 
      - input-remapper
      - langpacks-en 
      - neovim 
      - libvirt
      - virt-manager 
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-viewer
      - zsh
      - snapper
      - podman
      - podman-compose
      - fish
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - code
      - nmap
      - wine

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.discordapp.Discord
        - com.github.PintaProject.Pinta
        - com.github.tchx84.Flatseal
        - com.github.wwmm.easyeffects
        - com.google.Chrome
        - com.microsoft.Edge
        - com.nextcloud.desktopclient.nextcloud
        - com.slack.Slack
        - hu.irl.cameractrls
        - net.davidotek.pupgui2 
        - net.lutris.Lutris
        - org.freedesktop.Platform.VulkanLayer.gamescope
        - org.freedesktop.Platform.VulkanLayer.MangoHud
        - nz.mega.MEGAsync
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.kde.gwenview
        - org.kde.okular
        - org.kde.yakuake
        - org.mozilla.Thunderbird
        - org.onlyoffice.desktopeditors
        - org.qbittorrent.qBittorrent
        - org.remmina.Remmina
        - org.signal.Signal
        - org.speedcrunch.SpeedCrunch
        - org.videolan.VLC
        - uk.co.powdertoy.tpt

  - type: systemd
    system:
      enabled:
        - input-remapper.service

  - type: signing
