# image will be published to ghcr.io/<user>/<name>
name: namaste-os
# description will be included in the image's metadata
description: Personal distro by and for JFL

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - bridge-utils 
      - clblast 
      - clblast-devel 
      - distrobox 
      - input-remapper
      - langpacks-en 
      - v4l2loopback
      - akmod-v4l2loopback
      - neovim 
      - libvirt
      - virt-manager 
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-viewer
      - zsh
      - snapper
      - podman
      - podman-compose
      - fish
      # - micro
      # - starship

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - one.ablaze.floorp
        - com.discordapp.Discord
        - com.github.PintaProject.Pinta
        - com.github.tchx84.Flatseal
        - com.github.wwmm.easyeffects
        - com.google.Chrome
        - com.microsoft.Edge
        - com.nextcloud.desktopclient.nextcloud
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.BackgroundRemoval
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - com.slack.Slack
        - com.ultimaker.cura
        - net.lutris.Lutris
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2 
        - com.visualstudio.code
        - hu.irl.cameractrls
        - nz.mega.MEGAsync
        - org.chromium.Chromium
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.mozilla.Thunderbird
        - org.qbittorrent.qBittorrent
        - org.remmina.Remmina
        - org.signal.Signal
        - org.speedcrunch.SpeedCrunch
        - org.videolan.VLC
        - org.onlyoffice.desktopeditors
        - org.kde.okular
        - uk.co.powdertoy.tpt
        - us.zoom.Zoom
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog

  - type: script
    snippets:
      - "wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/bin/yt-dlp"
      - "chmod a+rx /usr/bin/yt-dlp"

  - type: systemd
    system:
      enabled:
        - input-remapper.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
