on:
  push:
    paths:
      - "boot_menu.yml"
      - ".github/workflows/release-iso.yml"
  workflow_dispatch:

name: build-iso-40
jobs:
  release-iso:
      name: Generate and Release ISOs
      runs-on: ubuntu-latest
      permissions:
        contents: write
      container:
        image: fedora:40
        options: --privileged
      steps:
      - name: Build Container Installer
        uses: JasonN3/build-container-installer@v1.2.1
            
